version: "3.9"

services:
  alice:
    build: .
    container_name: alice
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true

  bob:
    build: .
    container_name: bob
    ports:
      - "5001:5001"
    stdin_open: true
    tty: true
